version: 2

models:
    - name: stg_corebank_loans
      description: "A starter dbt model"
      columns:
          - name: loanid
            description: "The primary key for this table"
            tests:
                - unique

    - name: hub_loan
      description: "A starter dbt model"
      columns:
          - name: loanid
            description: "The primary key for this table"
            tests:
                - unique
